### ISSUE TITLE
gitlab支持issues的event吗

### ISSUE THREAD

**Issue by shibd** [LeoEatle/git-webhook-wework-robot#10]
如题

**Comment by cantgis** [comment]
gitlab 12.4.1 版本 貌似只支持push,
pr (Merge request events)  test 出现error:
`Hook execution failed: Ensure the project has merge requests.`

**Comment by LeoEatle** [comment]
> gitlab 12.4.1 版本 貌似只支持push,
> pr (Merge request events) test 出现error:
> `Hook execution failed: Ensure the project has merge requests.`

这个情况是Gitlab的内部错误

> gitlab支持issues的event吗

支持的，除非有新的事件类型或者gitlab API改变
