### ISSUE TITLE
尝试Serverless？

### ISSUE THREAD

**Issue by liuwenchao** [LeoEatle/git-webhook-wework-robot#11]
用Serverless可以简化很多，而且不需要花钱买服务器。

这里有个粗糙的，https://github.com/liuwenchao/wechat-work-bot-github

**Comment by LeoEatle** [comment]
很好的建议，我之后有空看看能否改成更易于用于Serverless的版本

**Comment by LeoEatle** [comment]
见 https://github.com/LeoEatle/git-webhook-wework-robot/pull/12
