### ISSUE TITLE
云函数不支持gitlab

### ISSUE THREAD

**Issue by ydCao** [LeoEatle/git-webhook-wework-robot#15]
使用云函数创建，貌似不支持gitlab。

**Comment by ydCao** [comment]
借鉴github云函数我自己编写了一个支持gitlab的云函数，我的问题已解决，谢谢

**Comment by wq163** [comment]
是的，日志看到返回Not a github webhook deliver，微信群机器人收不到消息

**Comment by wq163** [comment]
> 借鉴github云函数我自己编写了一个支持gitlab的云函数，我的问题已解决，谢谢

不提个PR么？

**Comment by LeoEatle** [comment]
当时确实没考虑到加gitlab支持，因为觉得大部分gitlab是内网可能连不上腾讯云，
**求PR**
完全可以把你的gitlab云函数加到`cloud`目录下，我来合并

**Comment by LeoEatle** [comment]
已支持
https://github.com/LeoEatle/git-webhook-wework-robot/commit/626eaa4d175f7f28cee39ddec4b699696866454e
