### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xinzhen2015** [LeoEatle/git-webhook-wework-robot#16]
<img width="837" alt="截屏2020-04-16 下午4 03 11" src="https://user-images.githubusercontent.com/15154948/79431370-f0ffbf00-7ffc-11ea-988c-1b77f33863c7.png">

这个报错不知道怎么解决 😭

**Comment by LeoEatle** [comment]
这是8080端口已经被占用，你需要检查下是不是已经开了个8080端口的node进程
可以用`lsof -i:8080`查询

**Comment by xinzhen2015** [comment]
> 这是8080端口已经被占用，你需要检查下是不是已经开了个8080端口的node进程
> 可以用`lsof -i:8080`查询

已经解决了~ 另外我想问下，之前的版本发的消息里面会有 更新的文件统计数，为啥新版的，没有这些信息了，

之前我是通过 WEBHOOK_URL_PROJ = 。。。。。。。。。npm start 这种方式启动的

**Comment by LeoEatle** [comment]
> 已经解决了~ 另外我想问下，之前的版本发的消息里面会有 更新的文件统计数，为啥新版的，没有这些信息了，
> 
> 之前我是通过 WEBHOOK_URL_PROJ = 。。。。。。。。。npm start 这种方式启动的

感觉你可能是用了个另一个服务...咱这服务特简单，没这个功能
看下 webhook 是不是同一个
