### ISSUE TITLE
api服务推送的消息样式错乱

### ISSUE THREAD

**Issue by AglaiaWang** [LeoEatle/git-webhook-wework-robot#39]
使用的服务：
[https://service-d6if097q-1251767583.gz.apigw.tencentcs.com/release/wechat-work-gitlab-robot?id={robotid}](https://service-d6if097q-1251767583.gz.apigw.tencentcs.com/release/wechat-work-gitlab-robot?id=%7Brobotid%7D)
样式截图：
<img width="306" alt="wecom-temp-9d04605c4823cb8b0cddd1c27c724b6b" src="https://user-images.githubusercontent.com/8652036/159864654-626c0c0e-8287-4b24-8946-2f3c9b9016c7.png">

**Comment by LeoEatle** [comment]
这是因为ES6的模板字符串在代码中被自动化格式，加了多余的空格，已经去掉了，可以试试
