### ISSUE TITLE
部署安装完配置env之后怎么使用？

### ISSUE THREAD

**Issue by sunsan05** [LeoEatle/git-webhook-wework-robot#5]
按照说明部署完了以后，修改了端口为18080 然后在gitlab的webhook内写的地址为
```
http://服务器地址:18080/gitlab?id=xxx
```
 但是无法使用。

---

```log
0|server  | info: POST /gitlab?id=xxxxx 403 1ms
0|server  | info: GET /gitlab?id=xxxxx 404 0ms
0|server  | info: POST /gitlab?id=xxxxx 404 0ms
```

**Comment by sunsan05** [comment]
```
interface IssueBody {
    user: User;
    repository: Repository;
    object_attributes: {
        id: number,
        title: string,
        created_at: string,
        updated_at: string,
        merge_status: string,
        description: string,
        url: string,
        state: string,
        action: string // action 可能是open/update/close/reopen
    };
}
```
看起来和Gitlab的issues hook里面返回的json key不匹配。

**Comment by cantgis** [comment]
gitlab如何配置?
请求打开issue

**Comment by LeoEatle** [comment]
如果是`gitlab`，url用`/git?id=xxx`就可以了

**Comment by cantgis** [comment]
readme上写的是gitab....
请更新一下！

**Comment by LeoEatle** [comment]
好，已更新readme #9

**Comment by cantgis** [comment]
> 如果是`gitlab`，url用`/git?id=xxx`就可以了

与gitlab集成hook,在gitlab配置页面添加URL下面的,Secret Token为为空,无SSL
http://172.0.1.7:8080/git?id=1fdsf2g1g3-921-4bff-bc5a-3r5423df09f2
单独浏览器访问上面URL：页面Not Found

集成gitlab后点击test测试，Push Events，gitlab 500 错误
Whoops, something went wrong on our end.
Try refreshing the page, or going back and attempting the action again.
Please contact your GitLab administrator if this problem persists.

**Comment by LeoEatle** [comment]
单独访问的确404，因为只监听了`POST`请求，而你浏览器访问是`GET`
```
router.post("/git", controller.gitlab.getWebhook);
```

后面gitlab的test问题，似乎是gitlab内部报错，看下gitlab的日志信息

**Comment by cantgis** [comment]
> 单独访问的确404，因为只监听了`POST`请求，而你浏览器访问是`GET`
> 
> ```
> router.post("/git", controller.gitlab.getWebhook);
> ```
> 
> 后面gitlab的test问题，似乎是gitlab内部报错，看下gitlab的日志信息

![image](https://user-images.githubusercontent.com/6498032/67262479-83545980-f4d7-11e9-9341-db6258323e8f.png)

**Comment by LeoEatle** [comment]
gitlab的webhook请求会带一些特有的HTTP头，比如`x-event`表示git事件，你用postman请求的话，我检测不到这个头信息就报错了。
不过至少说明服务起来了，你看下gitlab为何没能成功发起webhook请求吧。
